# Site Information
site_name: Smoke
site_url: https://gooseberry.github.io/smoke/
site_author: Eric Desgroseilliers

#  Repository
repo_name: gooseberry/smoke
repo_url: https://github.com/gooseberry/smoke

# Copyright
copyright: Copyright &copy; 2022 Eric Desgroseilliers

# Configuration
theme:
    name: material
    icon: 
        logo: material/gamepad-variant
        admonition:
            danger: material/heart
        
    palette:

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-3
            name: Switch to light mode


    # Features
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.top

# Extensions
markdown_extensions:
    - admonition
    - wikilinks
    - attr_list
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.snippets:
        base_path: 
            - "docs/assets/snippets"

# Page tree
nav:
    - Home: "index.md"
    - Getting Started: "getting-started.md"
    - Supported Games:
        - Descent II: "games/descent-2.md"
        - The Dig: "games/the-dig.md"
        - Doom: "games/doom.md"
        - Doom II: "games/doom-2.md"
        - Epic Pinball: "games/epic-pinball.md"
        - Final Doom: "games/final-doom.md"
        - Freespace 2: "games/freespace-2.md"
        - Gabriel Knight - Sins of the Fathers: "games/gabriel-knight.md"
        - Heretic - Shadow of the Serpent Riders: "games/heretic.md"
        - Hexen - Beyond Heretic: "games/hexen.md"
        - Indiana Jones and the Fate of Atlantis: "games/atlantis.md"
        - The Original Strife - Veteran Edition: "games/strife.md"
        - Quake: "games/quake.md"
        - Quake II: "games/quake-2.md"
        - Sam & Max Hit the Road: "games/sam-max.md"
        - Screamer 2: "games/screamer-2.md"
        - Theme Hospital: "games/theme-hospital.md"
        - Tie Fighter: "games/tie-fighter.md"
        - Torchlight II: "games/torchlight-2.md"
        - XCOM UFO Defense: "games/xcom-ufo-defense.md"
        - XCOM Terror from the Deep: "games/xcom-terror-from-the-deep.md"
    - Mods:
        - Quake:
            - Alkaline: "mods/alkaline.md"
            - Arcane Dimensions: "mods/arcane-dimensions.md"
            - Quake Brutalist Jam: "mods/quake-brutalist-jam.md"
    - About:
        - About: "about/about.md"
        - Philosophy: "about/philosophy.md"
        - Alternatives: "about/alternatives.md"
        - Appreciation: "about/appreciation.md"